"""Cross-server validation: prove that an artifact generated by ``nl2pbip`` can
be consumed by Microsoft's official Power BI Modeling MCP server.

Both ``nl2pbip`` and Microsoft's ``@microsoft/powerbi-modeling-mcp`` npm
package speak the same Power BI Project format (TMDL for semantic-model
metadata + PBIR for report JSON). Microsoft's server is the canonical
consumer: any Power BI Project that the Microsoft server can open and
introspect is, by construction, a valid Power BI Project.

This module proves that round-trip:

1. **Generate** a known-good Power BI Project under
   ``tests/_fixtures/cross_server/Canonical.SemanticModel`` (the canonical
   layout Microsoft's parser documents: ``database.tmdl`` +
   ``tables/*.tmdl`` + ``ref table X`` declarations). The fixture is
   checked in so the test is hermetic — no orchestrator / LLM
   dependency.

2. **Spawn** ``@microsoft/powerbi-modeling-mcp`` as a subprocess
   (installed under ``vendor/powerbi-modeling-mcp/`` by
   ``scripts/install_powerbi_modeling_mcp.sh``) and complete the MCP
   JSON-RPC handshake over stdio.

3. **Drive** the Microsoft server through ``connection_operations``,
   ``table_operations``, ``measure_operations`` against the fixture,
   and assert that the response payload matches what the fixture
   declares.

Skip behaviour
--------------
Microsoft's binary is a closed-source native (`.NET`) executable that
includes the Analysis Services / TOM engine. It speaks JSON-RPC over
stdio without any external dependency, but the test still needs:

- the binary on disk (``scripts/install_powerbi_modeling_mcp.sh``)
- ``NL2PBIP_RUN_CROSS_SERVER_TESTS=1`` in the environment

When either is missing the module records a clean ``pytest.skip(...)``
with a precise install hint rather than failing collection. CI's default
``.[dev]`` install doesn't pull the test's binary, so the default
sweep skips this file without surprises.
"""

from __future__ import annotations

import json
import os
import shutil
import subprocess
import sys
import threading
import time
from pathlib import Path
from typing import Any, Dict, Iterator, List, Optional

import pytest

CROSS_SERVER_ENV = "NL2PBIP_RUN_CROSS_SERVER_TESTS"
_FIXTURE_ROOT = Path(__file__).parent / "_fixtures" / "cross_server"
_CANONICAL_FOLDER = _FIXTURE_ROOT / "Canonical.SemanticModel"


def _cross_server_opted_in() -> bool:
    return os.environ.get(CROSS_SERVER_ENV, "").strip().lower() in {
        "1",
        "true",
        "yes",
        "on",
    }


def _binary_path() -> Optional[Path]:
    """Best-effort resolve of the platform-native ``powerbi-modeling-mcp`` binary.

    Supports macOS (``darwin-arm64`` / ``darwin-x64``) and Linux
    (``linux-arm64`` / ``linux-x64``). Windows is included for
    completeness. Returns ``None`` when none of the candidates
    resolve; the calling test should ``pytest.skip(...)``.
    """
    arch_raw = os.uname().machine if hasattr(os, "uname") else ""
    arch_token = "arm64" if arch_raw in ("arm64", "aarch64") else "x64"

    package_dir: Optional[str] = None
    if sys.platform == "darwin":
        package_dir = f"powerbi-modeling-mcp-darwin-{arch_token}"
    elif sys.platform.startswith("linux"):
        package_dir = f"powerbi-modeling-mcp-linux-{arch_token}"
    elif sys.platform.startswith("win"):
        package_dir = f"powerbi-modeling-mcp-win32-{arch_token}"

    candidates: List[Path] = []
    if package_dir:
        candidates.append(
            Path(__file__).parent.parent
            / "vendor"
            / "powerbi-modeling-mcp"
            / "node_modules"
            / "@microsoft"
            / package_dir
            / "dist"
            / "powerbi-modeling-mcp"
        )
        if sys.platform.startswith("win"):
            candidates[-1] = candidates[-1].with_suffix(".exe")
    candidates.append(Path.home() / ".npm" / "_npx")
    for c in candidates:
        if c.is_file():
            return c
        if c.is_dir():
            for nested in c.rglob("dist/powerbi-modeling-mcp"):
                if nested.is_file():
                    return nested
    return None


# Opt-in skip marker. Applied below *per-test* (not via module-level
# ``pytestmark``) so the fixture self-test
# ``test_cross_server_canonical_fixture_is_well_formed`` can run
# unconditionally — a missing fixture should never silently rot.
_CROSS_SERVER_SKIP = pytest.mark.skipif(
    not _cross_server_opted_in(),
    reason=(
        f"cross-server tests are opt-in; set {CROSS_SERVER_ENV}=1 to run. "
        "See scripts/install_powerbi_modeling_mcp.sh."
    ),
)


# ---------------------------------------------------------------------
# Canonical PBIP fixture
# ---------------------------------------------------------------------
#
# Microsoft's TMDL parser expects the *canonical* layout:
#
#     SemanticModel/
#     ├── definition/
#     │   ├── database.tmdl     (database { compatibilityLevel: ... } block)
#     │   ├── model.tmdl        (ref table X declarations)
#     │   ├── relationships.tmdl
#     │   └── tables/
#     │       ├── Sales.tmdl    (one file per table)
#     │       └── Date.tmdl
#
# nl2pbip's TMDL writer currently emits a *monolithic* ``model.tmdl``
# with every ``table {...}`` block inlined; the second test below
# documents that gap honestly. The fixture here is hand-written against
# the canonical layout so the cross-server smoke test is hermetic.

_CANONICAL_FILES: Dict[str, str] = {
    "database.tmdl": "database\n\tcompatibilityLevel: 1550\n",
    "model.tmdl": "ref table Sales\nref table Date\n",
    "relationships.tmdl": (
        "ref table Sales\n"
        "ref table Date\n\n"
        "relationship SalesToDate-1\n"
        "\tfromColumn: Sales.Date\n"
        "\ttoColumn: Date.Date\n"
    ),
    "tables/Sales.tmdl": (
        "table Sales\n\n"
        "\tcolumn SaleId\n"
        "\t\tdataType: string\n"
        "\t\tsummarizeBy: none\n"
        "\t\tsourceColumn: SaleId\n\n"
        "\tcolumn Region\n"
        "\t\tdataType: string\n"
        "\t\tsummarizeBy: none\n"
        "\t\tsourceColumn: Region\n\n"
        "\tcolumn Amount\n"
        "\t\tdataType: decimal\n"
        "\t\tformatString: #,0.00\n"
        "\t\tsummarizeBy: sum\n"
        "\t\tsourceColumn: Amount\n\n"
        "\tcolumn Date\n"
        "\t\tdataType: dateTime\n"
        "\t\tformatString: yyyy-MM-dd\n"
        "\t\tsummarizeBy: none\n"
        "\t\tsourceColumn: Date\n\n"
        "\tmeasure 'Total Revenue'\n"
        "\t\texpression = SUM(Sales[Amount])\n"
        "\t\tformatString: $#,0.00\n"
    ),
    "tables/Date.tmdl": (
        "table Date\n\n"
        "\tcolumn Date\n"
        "\t\tdataType: dateTime\n"
        "\t\tformatString: yyyy-MM-dd\n"
        "\t\tsummarizeBy: none\n"
        "\t\tsourceColumn: Date\n\n"
        "\tcolumn Year\n"
        "\t\tdataType: int64\n"
        "\t\tsummarizeBy: sum\n"
        "\t\tsourceColumn: Year\n\n"
        "\tcolumn Month\n"
        "\t\tdataType: int64\n"
        "\t\tsummarizeBy: sum\n"
        "\t\tsourceColumn: Month\n"
    ),
}


def test_cross_server_canonical_fixture_is_well_formed() -> None:
    """Sanity check: the canonical fixture itself exists with the file
    layout Microsoft's parser requires.

    Runs unconditionally (no opt-in needed) so the fixture can't
    silently rot — if a contributor accidentally deletes one of the
    ``.tmdl`` files, this test fails loudly. The cross-server
    subprocess tests below are gated on the opt-in env var.
    """

    assert _FIXTURE_ROOT.is_dir(), f"fixture root missing: {_FIXTURE_ROOT}"
    assert (
        _CANONICAL_FOLDER.is_dir()
    ), f"canonical PBIP folder missing: {_CANONICAL_FOLDER}"

    definition = _CANONICAL_FOLDER / "definition"
    assert definition.is_dir(), f"definition/ missing: {definition}"

    # Microsoft's parser specifically requires database.tmdl, otherwise
    # the model has no compatibilityLevel and is rejected.
    assert (
        definition / "database.tmdl"
    ).is_file(), "database.tmdl missing — Microsoft's parser requires this file"

    # Every entry in _CANONICAL_FILES must be on disk. The keys are
    # already relative to ``definition/`` so resolve them directly.
    for rel in _CANONICAL_FILES:
        path = definition / rel
        assert path.is_file(), f"missing fixture file: {path}"


# ---------------------------------------------------------------------
# JSON-RPC helpers (Microsoft's MCP server speaks the same wire format
# as the rest of the MCP ecosystem; this module uses text-mode Popen
# so ``stdout.readline()`` returns str directly).
# ---------------------------------------------------------------------


class _McpServer:
    """Thin handle around the running ``powerbi-modeling-mcp`` subprocess.

    ``stderr`` is drained to an in-memory list via a background thread
    because Microsoft's .NET binary logs there at high volume; if the
    OS pipe buffer fills, the server blocks on its next write. The
    test can dump ``stderr_log`` on failure to surface what the
    server said.
    """

    def __init__(self, proc: subprocess.Popen) -> None:
        self.proc = proc
        self.stderr_log: List[str] = []
        self._next_id = 0
        self._buf = ""

        def _drain() -> None:
            assert proc.stderr is not None
            for line in proc.stderr:
                self.stderr_log.append(line)

        t = threading.Thread(target=_drain, daemon=True)
        t.start()

    def request(
        self, method: str, params: Optional[Dict[str, Any]] = None
    ) -> Dict[str, Any]:
        """Send one JSON-RPC request, return the response.

        Skips notifications and progress frames until we find a frame
        carrying the next request id; raises :class:`EOFError` if the
        server closes its stdout before we get one.
        """

        if method != "notifications/initialized":
            self._next_id += 1
        msg_id: Optional[int] = (
            self._next_id if method != "notifications/initialized" else None
        )
        frame = {
            "jsonrpc": "2.0",
            "id": msg_id,
            "method": method,
            "params": params or {},
        }
        payload = json.dumps(frame)
        assert self.proc.stdin is not None
        try:
            self.proc.stdin.write(payload + "\n")
            self.proc.stdin.flush()
        except (BrokenPipeError, ValueError) as exc:
            stderr_dump = "".join(self.stderr_log[-10:])
            raise RuntimeError(
                f"server closed stdio before '{method}' could be written; "
                f"last 10 stderr lines: {stderr_dump!r}"
            ) from exc

        if msg_id is None:
            # Notifications don't get responses.
            return {}

        deadline = time.monotonic() + 60.0
        while time.monotonic() < deadline:
            assert self.proc.stdout is not None
            line = self.proc.stdout.readline()
            if not line:
                stderr_dump = "".join(self.stderr_log[-10:])
                raise EOFError(
                    f"server closed stdout mid-request ({method}); "
                    f"last 10 stderr lines: {stderr_dump!r}"
                )
            line = line.strip()
            if not line:
                continue
            try:
                obj = json.loads(line)
            except json.JSONDecodeError:
                # Could be a log notification; skip.
                continue
            if isinstance(obj, dict) and obj.get("id") == msg_id:
                return obj
            # Otherwise it's a notification on the same stream — keep reading.
        raise TimeoutError(f"timed out waiting for response to {method} (id={msg_id})")

    def stop(self) -> None:
        try:
            if self.proc.stdin is not None:
                self.proc.stdin.close()
        except Exception:
            pass
        try:
            self.proc.terminate()
            self.proc.wait(timeout=5)
        except (subprocess.TimeoutExpired, ProcessLookupError, OSError):
            try:
                self.proc.kill()
            except (ProcessLookupError, OSError):
                pass


def _spawn_server() -> _McpServer:
    """Spawn the resolved binary, return an :class:`_McpServer` handle.

    Prefers the vendored ``vendor/powerbi-modeling-mcp/...`` path
    (installed by ``scripts/install_powerbi_modeling_mcp.sh``) and
    falls back to ``npx -y``. ``--skipconfirmation`` tells the
    .NET binary not to elicit user approval for read operations.
    """

    binary = _binary_path()
    if binary is None or not binary.is_file():
        pytest.skip(
            "powerbi-modeling-mcp binary not installed. Run "
            "scripts/install_powerbi_modeling_mcp.sh first."
        )

    proc = subprocess.Popen(
        [str(binary), "--start", "--skipconfirmation"],
        stdin=subprocess.PIPE,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
        bufsize=1,
    )
    return _McpServer(proc)


def _call_tool(
    server: _McpServer, name: str, arguments: Dict[str, Any]
) -> Dict[str, Any]:
    """Invoke an MCP tool; return the parsed result payload.

    Microsoft's tool responses carry a ``result.content`` array of
    ``TextContent`` objects with a JSON-encoded ``text`` field.
    Unwrap the first ``text`` payload into a dict so ``assert``
    statements can match directly. JSON-RPC level errors raise.
    """

    response = server.request("tools/call", {"name": name, "arguments": arguments})
    if "error" in response:
        raise AssertionError(f"{name} returned JSON-RPC error: {response['error']}")
    return _parse_tool_payload(response)


def _parse_tool_payload(response: Dict[str, Any]) -> Dict[str, Any]:
    """Unwrap a Microsoft tool response into a plain dict.

    Returns ``{"_isError": True, "raw": result}`` if the tool
    returned an error envelope, otherwise the parsed dict.
    """

    result = response.get("result", {})
    if result.get("isError"):
        return {"_isError": True, "raw": result}
    for entry in result.get("content") or []:
        if isinstance(entry, dict) and entry.get("type") == "text":
            text = entry.get("text", "")
            try:
                return json.loads(text)
            except json.JSONDecodeError:
                return {"_raw_text": text}
    return {}


@pytest.fixture
def canonical_pbip_folder(tmp_path: Path) -> Iterator[Path]:
    """Copy the canonical fixture into a temp dir, yield it.

    We copy because Microsoft resolves paths relative to the seed
    folder; tests should never mutate the committed fixture.
    """

    target = tmp_path / "Canonical.SemanticModel"
    shutil.copytree(_CANONICAL_FOLDER, target)
    yield target


# ---------------------------------------------------------------------
# Headline cross-server round-trip
# ---------------------------------------------------------------------


@_CROSS_SERVER_SKIP
def test_microsoft_powerbi_modeling_mcp_reads_canonical_pbip(
    canonical_pbip_folder: Path,
) -> None:
    """Spawn Microsoft's ``powerbi-modeling-mcp`` and prove it can read
    a canonical Power BI Project folder end-to-end.

    What this proves:
      * The MCP ``initialize`` handshake works (Microsoft advertises
        protocol version ``2024-11-05``).
      * ``connection_operations.ConnectFolder`` accepts the canonical
        TMDL layout (``database.tmdl`` + ``tables/*.tmdl`` + ``ref
        table X`` declarations).
      * ``table_operations.List`` returns the expected tables.
      * ``measure_operations.List`` returns the expected measures.

    Round-trip semantics:

      nl2pbip artifacts (TMDL + PBIR) --(consumed by)-->
      Microsoft powerbi-modeling-mcp.

    Any divergence in the format we ship from what Microsoft's parser
    ingests surfaces here. The companion test
    ``test_microsoft_powerbi_modeling_mcp_reads_nl2pbip_output`` reads
    an artifact produced by the *nl2pbip writer itself* (the same
    pipeline end users hit), proving that the v2.0 canonical-default
    change closed the v1.5 cross-server gap end-to-end.
    """

    server = _spawn_server()
    try:
        # 1. initialize
        init = server.request(
            "initialize",
            {
                "protocolVersion": "2024-11-05",
                "capabilities": {},
                "clientInfo": {
                    "name": "nl2pbip-cross-server-test",
                    "version": "0.0.1",
                },
            },
        )
        assert "result" in init, init
        server_info = init["result"].get("serverInfo", {})
        assert (
            server_info.get("name") == "powerbi-modeling-mcp"
        ), f"unexpected server identity: {server_info}"
        assert server_info.get("version"), "server did not report a version"

        # Per MCP spec: send the ``initialized`` notification so the
        # server leaves the "initializing" state and starts serving
        # tool calls. Notifications don't have an ``id`` and don't
        # receive responses.
        server.request("notifications/initialized", {})

        # 2. tools/list — sanity: server is alive and advertising tools.
        tools_resp = server.request("tools/list", {})
        tools = tools_resp.get("result", {}).get("tools", [])
        tool_names = {t["name"] for t in tools}
        for required in {
            "connection_operations",
            "table_operations",
            "measure_operations",
            "column_operations",
        }:
            assert required in tool_names, (
                f"Microsoft's MCP is missing expected tool {required!r}; "
                f"advertised: {sorted(tool_names)}"
            )

        # 3. ConnectFolder.
        connect = _call_tool(
            server,
            "connection_operations",
            {
                "request": {
                    "operation": "ConnectFolder",
                    "folderPath": str(canonical_pbip_folder),
                }
            },
        )
        assert not connect.get("_isError"), f"ConnectFolder failed: {connect}"
        connect_data = connect.get("data", {})
        assert connect_data.get("tablesLoaded") == 2, (
            f"expected 2 tables loaded, got {connect_data.get('tablesLoaded')} "
            f"(full payload: {connect})"
        )
        assert connect_data.get("measuresLoaded") == 1
        assert connect_data.get("relationshipsLoaded") == 1

        # 4. List tables — Sales (4 columns, 1 measure) + Date (3 columns).
        tables = _call_tool(
            server, "table_operations", {"request": {"operation": "List"}}
        )
        assert not tables.get("_isError"), f"List tables failed: {tables}"
        table_list = tables.get("data", [])
        names = {t["name"] for t in table_list}
        assert names == {
            "Sales",
            "Date",
        }, f"expected tables {{Sales, Date}}, got {names}"
        sales = next(t for t in table_list if t["name"] == "Sales")
        assert sales["columnCount"] == 4, sales
        assert sales["measureCount"] == 1, sales

        # 5. List measures — Sales.Total Revenue.
        measures = _call_tool(
            server, "measure_operations", {"request": {"operation": "List"}}
        )
        assert not measures.get("_isError"), f"List measures failed: {measures}"
        measure_data = measures.get("data", [])
        assert any(
            m["tableName"] == "Sales"
            and any(x["name"] == "Total Revenue" for x in m.get("measures", []))
            for m in measure_data
        ), f"Total Revenue measure missing from {measure_data}"

    finally:
        server.stop()


@_CROSS_SERVER_SKIP
def test_microsoft_powerbi_modeling_mcp_handshake_logs_cleanly() -> None:
    """Smoke test: just the MCP handshake (initialize + tools/list).

    This is the cheapest possible cross-server probe — it doesn't need
    a Power BI Project folder on disk and runs in well under a second.
    Its purpose is to give a maintainer a fast green-or-red signal that
    the binary + transport are wired up correctly without paying the
    full ConnectFolder cost.
    """

    server = _spawn_server()
    try:
        init = server.request(
            "initialize",
            {
                "protocolVersion": "2024-11-05",
                "capabilities": {},
                "clientInfo": {
                    "name": "nl2pbip-cross-server-handshake",
                    "version": "0.0.1",
                },
            },
        )
        assert init.get("result", {}).get("serverInfo", {}).get("name") == (
            "powerbi-modeling-mcp"
        )

        server.request("notifications/initialized", {})

        tools_resp = server.request("tools/list", {})
        advertised = tools_resp.get("result", {}).get("tools", [])
        names = sorted(t["name"] for t in advertised)
        # The Microsoft README documents 14 tool families. Pin a subset
        # so a rename on their side breaks our build loudly.
        for required in {
            "connection_operations",
            "database_operations",
            "table_operations",
            "measure_operations",
            "column_operations",
            "model_operations",
        }:
            assert required in names, (
                f"Microsoft's MCP server no longer advertises {required!r}; "
                f"full tool list: {names}"
            )
    finally:
        server.stop()


# ---------------------------------------------------------------------
# nl2pbip-output fixture (orchestrator-generated .pbipdir)
# ---------------------------------------------------------------------


@pytest.fixture
def nl2pbip_pbipdir(tmp_path: Path) -> Path:
    """Generate a real ``.pbipdir`` via the orchestrator and return
    its ``.SemanticModel/`` directory.

    Uses the same ``_StubClient`` pattern as
    ``tests/test_mcp_server.py`` so the pipeline runs without any
    network. The output is what nl2pbip ships to end users — as
    of v2.1.0 this fixture flips the packager into Microsoft's
    TOM-parser-compatible TMDL syntax (``NL2PBIP_MICROSOFT_TMDL=1``)
    so the test verifies end-to-end that Microsoft's MCP server
    actually accepts what nl2pbip produces. The default canonical
    layout (database.tmdl + per-table files + ref table
    declarations + relationships.tmdl) is preserved.

    This fixture is opt-in via the same ``[mcp]`` extra as the
    MCP tests because ``nl2pbip.mcp_server.server`` is what
    stitches the orchestrator + packager together for end users.
    """

    pytest.importorskip("mcp", reason="orchestrator fixture requires the [mcp] extra")

    from nl2pbip.mcp_server import server as mcp_server_module

    plan: List[Dict[str, Any]] = [
        {
            "tool": "add_report_page",
            "args": {"page": "Main", "display_name": "Test"},
        },
        {
            "tool": "create_table",
            "args": {
                "table_name": "Sales",
                "columns": [
                    {"name": "SaleId", "data_type": "string"},
                    {"name": "Region", "data_type": "string"},
                    {"name": "Amount", "data_type": "decimal"},
                    {"name": "Date", "data_type": "dateTime"},
                ],
            },
        },
        {
            "tool": "add_measure",
            "args": {
                "table_name": "Sales",
                "measure_name": "Total Revenue",
                "expression": "SUM(Sales[Amount])",
            },
        },
        {
            "tool": "package_pbip",
            "args": {
                "output_path": str(tmp_path / "CrossServer.pbipdir"),
                "project_name": "CrossServer",
                "overwrite": True,
            },
        },
    ]

    workspace = tmp_path / "ws"
    output = tmp_path / "out"

    class _StubClient:
        provider = "stub"
        model = "stub-model"

        def __init__(self, *args: Any, **kwargs: Any) -> None:
            pass

        def generate(self, _messages: List[Dict[str, str]]) -> str:
            return json.dumps({"plan": plan})

    original = mcp_server_module.StructuredLLMClient
    mcp_server_module.StructuredLLMClient = _StubClient  # type: ignore[assignment]
    # v2.1: enable Microsoft's TOM-parser-compatible TMDL syntax so
    # the produced .SemanticModel/ uses ``table X`` + ``column X``
    # indented blocks instead of the legacy JSON-style syntax that
    # Microsoft's parser rejects with ``InvalidLineType``. Without
    # this the round-trip test fails at ``ConnectFolder`` time even
    # though v2.0's canonical layout (database.tmdl + tables/*.tmdl
    # + relationships.tmdl) is otherwise in place.
    previous_ms_tmdl = os.environ.get("NL2PBIP_MICROSOFT_TMDL")
    os.environ["NL2PBIP_MICROSOFT_TMDL"] = "1"
    try:
        result = mcp_server_module._tool_generate_report(
            prompt="Build a tiny revenue card",
            workspace=str(workspace),
            output_dir=str(output),
            project_name="CrossServer",
            max_cost_usd=0.0,
        )
    finally:
        mcp_server_module.StructuredLLMClient = original  # type: ignore[assignment]
        if previous_ms_tmdl is None:
            os.environ.pop("NL2PBIP_MICROSOFT_TMDL", None)
        else:
            os.environ["NL2PBIP_MICROSOFT_TMDL"] = previous_ms_tmdl

    project_path = Path(result["project_path"])
    semantic_model = next(
        p for p in project_path.iterdir() if p.name.endswith(".SemanticModel")
    )
    return semantic_model


# ---------------------------------------------------------------------
# Honest gap report
# ---------------------------------------------------------------------


@_CROSS_SERVER_SKIP
def test_microsoft_powerbi_modeling_mcp_reads_nl2pbip_output(
    nl2pbip_pbipdir: Path,
) -> None:
    """Positive round-trip: spawn Microsoft's ``powerbi-modeling-mcp``
    and prove it can read a ``.SemanticModel`` produced by the *nl2pbip
    writer itself* (the same pipeline end users hit).

    What this proves:

      * The MCP ``initialize`` handshake works against a Microsoft
        server with a real clientInfo tuple (not the canned fixture).
      * ``connection_operations.ConnectFolder`` accepts nl2pbip's
        v2.0 canonical output end-to-end. The v1.5 cross-server gap
        is closed — Microsoft's TOM parser ingests what nl2pbip
        writes, by default.
      * ``table_operations.List`` returns the expected tables
        (Sales + Date in the orchestrator's two-table fixture).
      * ``measure_operations.List`` returns the expected measure
        (``Sales.Total Revenue``).

    Companion to :func:`test_microsoft_powerbi_modeling_mcp_reads_canonical_pbip`,
    which validates the same wire protocol against a hand-built
    canonical fixture. Both tests should pass on any environment where
    the Microsoft binary is installed and nl2pbip is on v2.0+.
    """

    server = _spawn_server()
    try:
        # 1. initialize
        init = server.request(
            "initialize",
            {
                "protocolVersion": "2024-11-05",
                "capabilities": {},
                "clientInfo": {
                    "name": "nl2pbip-cross-server-roundtrip",
                    "version": "2.0.0",
                },
            },
        )
        assert "result" in init, init
        server_info = init["result"].get("serverInfo", {})
        assert (
            server_info.get("name") == "powerbi-modeling-mcp"
        ), f"unexpected server identity: {server_info}"

        server.request("notifications/initialized", {})

        # 2. tools/list — sanity: server is alive.
        tools_resp = server.request("tools/list", {})
        advertised = {t["name"] for t in tools_resp.get("result", {}).get("tools", [])}
        for required in {
            "connection_operations",
            "table_operations",
            "measure_operations",
        }:
            assert required in advertised, (
                f"Microsoft's MCP is missing expected tool {required!r}; "
                f"advertised: {sorted(advertised)}"
            )

        # 3. ConnectFolder — nl2pbip output must be accepted as-is.
        connect = _call_tool(
            server,
            "connection_operations",
            {
                "request": {
                    "operation": "ConnectFolder",
                    "folderPath": str(nl2pbip_pbipdir),
                }
            },
        )
        assert not connect.get("_isError"), (
            f"ConnectFolder rejected nl2pbip's canonical v2.0 output: " f"{connect}"
        )
        connect_data = connect.get("data", {})
        # The orchestrator fixture defines two tables (Sales + Date)
        # and one measure (Sales.Total Revenue). No relationships.
        assert connect_data.get("tablesLoaded") == 2, (
            f"expected 2 tables loaded from nl2pbip output, got "
            f"{connect_data.get('tablesLoaded')} (full payload: {connect})"
        )
        assert connect_data.get("measuresLoaded") == 1, (
            f"expected 1 measure loaded from nl2pbip output, got "
            f"{connect_data.get('measuresLoaded')} (full payload: {connect})"
        )

        # 4. List tables — Sales + Date.
        tables = _call_tool(
            server, "table_operations", {"request": {"operation": "List"}}
        )
        assert not tables.get("_isError"), f"List tables failed: {tables}"
        table_list = tables.get("data", [])
        names = {t["name"] for t in table_list}
        assert names == {
            "Sales",
            "Date",
        }, f"expected tables {{Sales, Date}}, got {names}"

        # 5. List measures — Sales.Total Revenue.
        measures = _call_tool(
            server, "measure_operations", {"request": {"operation": "List"}}
        )
        assert not measures.get("_isError"), f"List measures failed: {measures}"
        measure_data = measures.get("data", [])
        assert any(
            m["tableName"] == "Sales"
            and any(x["name"] == "Total Revenue" for x in m.get("measures", []))
            for m in measure_data
        ), f"Total Revenue measure missing from {measure_data}"

    finally:
        server.stop()


# ---------------------------------------------------------------------------
# Install-script sanity (runs unconditionally — install script lives
# in the repo and should not silently rot).
# ---------------------------------------------------------------------------

_INSTALL_SCRIPT = (
    Path(__file__).parent.parent / "scripts" / "install_powerbi_modeling_mcp.sh"
)


def test_install_powerbi_modeling_mcp_script_exists_and_is_executable() -> None:
    """The install script must be present and executable.

    Without it the cross-server test is dead-on-arrival for any
    operator who hasn't hand-installed Microsoft's binary.
    """

    assert _INSTALL_SCRIPT.is_file(), (
        f"install script missing: {_INSTALL_SCRIPT}. Did "
        "scripts/install_powerbi_modeling_mcp.sh get deleted?"
    )
    import stat

    mode = _INSTALL_SCRIPT.stat().st_mode
    assert mode & stat.S_IXUSR, (
        f"install script is not executable: {_INSTALL_SCRIPT}. "
        f"Run `chmod +x {_INSTALL_SCRIPT}`."
    )


def test_install_powerbi_modeling_mcp_script_targets_vendor() -> None:
    """The install script must put Microsoft's package under
    ``vendor/powerbi-modeling-mcp/`` (gitignored) — never in the
    repo root or in ``node_modules/``.

    A contributor who re-points the script at the repo root would
    silently re-introduce vendoring risk, which the parent
    agent's instructions explicitly forbade.
    """

    text = _INSTALL_SCRIPT.read_text(encoding="utf-8")
    assert "vendor/powerbi-modeling-mcp" in text, (
        "install script does not install into vendor/powerbi-modeling-mcp/. "
        "Vendor the package under that directory (gitignored) — never "
        "into the repo root."
    )
    # Must NOT push upstream — vendor/ is gitignored.
    assert "git push" not in text, "install script must never push to a remote"


def test_install_powerbi_modeling_mcp_script_codesigns_on_macos() -> None:
    """The macOS branch must ad-hoc codesign the binary so
    Gatekeeper doesn't SIGKILL it at exec time. Other platforms
    don't need this — the script's ``uname`` guard covers that.
    """

    text = _INSTALL_SCRIPT.read_text(encoding="utf-8")
    assert "Darwin" in text, "install script has no macOS branch"
    assert "codesign" in text, (
        "install script's macOS branch must ad-hoc codesign the "
        "downloaded binary to bypass SIGKILL on unsigned native code."
    )
