"""High-level ``.pbit`` archive builder.

:class:`PbitArchiveBuilder` is the public API for constructing a
Power BI Desktop template archive. Callers:

1. Instantiate the builder with a destination path.
2. Add ``DataModelSchema``, ``DataMashup``, ``Report/Layout``,
   custom visuals, and static resources via the typed ``add_*``
   methods.
3. Call :meth:`finalize` to write ``[Content_Types].xml`` and any
   missing manifest parts (``Version``, ``Metadata``, ``Settings``,
   ``SecurityBindings``, ``DiagramLayout``), then close the archive.

The builder enforces OPC correctness:

* Forward-slash paths (``Report/Layout``, not ``Report\\Layout``).
* UTF-8 BOM prefix on ``[Content_Types].xml``.
* Standard Power BI Override entries for known parts.
* ``Default`` entries for common file extensions.

It also enforces Power BI conventions:

* ``Version`` is a single byte (``b"1"``).
* ``DataMashup`` starts with the 8-byte magic header.
* ``DataModelSchema`` is JSON with ``compatibilityLevel`` and
  ``model.culture``.
* Custom visuals are placed under ``Report/CustomVisuals/<name>/``
  with ``package.json`` + ``resources/<name>.pbiviz.json``.

Use :meth:`add_pbip_folder` to ingest a complete PBIP folder
(``*.SemanticModel`` + ``*.Report`` + ``*.pbip`` opener) in a
single call — that's the typical pipeline integration.
"""

from __future__ import annotations

import json
import zipfile
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, Iterable, Optional

from nl2pbip.exporter.opc import (
    _ContentTypeRegistry,
    make_data_mashup_stub,
    make_data_model_schema_template,
    make_diagram_layout_json,
    make_metadata_json,
    make_minimal_data_model_schema,
    make_security_bindings_json,
    make_settings_json,
)


@dataclass
class PbitArchiveBuilder:
    """Build a Power BI Desktop ``.pbit`` archive.

    Parameters
    ----------
    output_path:
        Destination ``.pbit`` file. Created or overwritten on
        :meth:`finalize`.
    template_name:
        Display name written into ``Metadata.json`` and
        ``DataModelSchema``.
    culture:
        Model culture (``en-US`` by default).
    """

    output_path: Path
    template_name: str = "nl2pbip Generated Model"
    culture: str = "en-US"
    description: str = "Template generated by nl2pbip."

    _archive: Optional[zipfile.ZipFile] = field(default=None, init=False)
    _parts: Dict[str, bytes] = field(default_factory=dict, init=False)
    _registry: _ContentTypeRegistry = field(init=False)
    _finalised: bool = field(default=False, init=False)
    _logger: Any = field(default=None, init=False, repr=False)

    def __post_init__(self) -> None:
        self.output_path = Path(self.output_path)
        self.output_path.parent.mkdir(parents=True, exist_ok=True)
        self._registry = _ContentTypeRegistry.for_power_bi()
        self._logger = _build_logger()

    # ------------------------------------------------------------------
    # Lifecycle
    # ------------------------------------------------------------------
    def add_part(self, part_path: str, body: bytes, content_type: str = "") -> None:
        """Add a raw part to the archive.

        ``part_path`` uses forward slashes (e.g. ``Report/Layout``).
        ``content_type`` overrides the auto-detected MIME; leave empty
        to let the registry pick one based on file extension.
        """
        if self._finalised:
            raise RuntimeError("Cannot add parts after finalize().")
        # Normalise: forward slashes only, no leading slash (zipfile
        # uses relative paths).
        normalised = part_path.replace("\\", "/").lstrip("/")
        if not normalised:
            raise ValueError("part_path must be non-empty.")
        self._parts[normalised] = body
        if content_type:
            self._registry.add_override(normalised, content_type)
        else:
            # Auto-register an Override for the part so Power BI
            # Desktop can look it up by path. The Default entry
            # covers extension-based dispatch when the Override is
            # absent, but Power BI's template loader is strict.
            ext = normalised.rsplit(".", 1)[-1].lower() if "." in normalised else ""
            if ext and ext in self._registry.defaults:
                self._registry.add_override(normalised, self._registry.defaults[ext])

    def add_json_part(self, part_path: str, payload: Any) -> None:
        """Serialise ``payload`` as JSON and add it as a part."""
        body = json.dumps(payload, indent=2).encode("utf-8")
        self.add_part(part_path, body, content_type="application/json")

    # ------------------------------------------------------------------
    # Convenience helpers for the canonical Power BI parts
    # ------------------------------------------------------------------
    def add_version(self, value: bytes = b"1") -> None:
        self.add_part("Version", value, content_type="application/json")

    def add_metadata(self, **overrides: Any) -> None:
        payload = make_metadata_json(
            title=overrides.get("title", self.template_name),
            description=overrides.get("description", self.description),
            created=overrides.get("created", ""),
            generator=overrides.get("generator", "nl2pbip"),
        )
        self.add_json_part("Metadata", payload)

    def add_settings(self, payload: Optional[Dict[str, Any]] = None) -> None:
        self.add_json_part("Settings", payload or make_settings_json())

    def add_security_bindings(self, payload: Optional[Dict[str, Any]] = None) -> None:
        self.add_json_part("SecurityBindings", payload or make_security_bindings_json())

    def add_diagram_layout(self, payload: Optional[Dict[str, Any]] = None) -> None:
        self.add_json_part("DiagramLayout", payload or make_diagram_layout_json())

    def add_data_model_schema(self, payload: Optional[Dict[str, Any]] = None) -> None:
        """Add the ``DataModelSchema`` Tabular Model JSON part.

        ``payload`` is the TMSL document. If omitted, a minimal
        shell is generated that Power BI Desktop will accept as a
        template.
        """
        if payload is None:
            payload = make_minimal_data_model_schema(name=self.template_name)
        self.add_json_part("DataModelSchema", payload)

    def add_data_model_schema_template(self) -> None:
        """Add the legacy ``DataModelSchemaTemplate.json`` part.

        Real Power BI Desktop archives put the model schema in
        ``DataModelSchema`` instead, but some readers (and the
        legacy ``export_as_pbit_zip`` exporter) still expect this
        file. We emit both for compatibility.
        """
        self.add_json_part(
            "DataModelSchemaTemplate.json",
            make_data_model_schema_template(name=self.template_name),
        )

    def add_data_mashup(self, body: Optional[bytes] = None) -> None:
        """Add the ``DataMashup`` Power Query stream.

        ``body`` should start with the 8-byte magic header
        (``\\x01\\x00\\x00\\x00\\x01\\x00\\x00\\x00``) and contain an
        embedded OPC ZIP of Power Query M expressions. When omitted,
        a minimal stub with just the header is emitted so Power BI
        Desktop recognises the part.
        """
        self.add_part(
            "DataMashup",
            body if body is not None else make_data_mashup_stub(),
            content_type="application/octet-stream",
        )

    def add_report_layout(self, payload: Any) -> None:
        """Add the ``Report/Layout`` JSON describing the report.

        ``payload`` is the report layout JSON — for a PBIP-derived
        template this is the merged page/visual representation.
        """
        self.add_json_part("Report/Layout", payload)

    def add_report_linguistic_schema(self, payload: Any) -> None:
        """Add the ``Report/LinguisticSchema`` part (XML)."""
        if isinstance(payload, bytes):
            body = payload
        else:
            body = json.dumps(payload, indent=2).encode("utf-8")
        self.add_part("Report/LinguisticSchema", body, content_type="application/xml")

    # ------------------------------------------------------------------
    # File ingestion helpers
    # ------------------------------------------------------------------
    def add_file(self, source_path: Path, archive_path: str = "") -> None:
        """Read ``source_path`` from disk and add it as a part.

        ``archive_path`` defaults to the relative form of
        ``source_path``; pass an explicit value to remap the path
        inside the archive.
        """
        source = Path(source_path)
        if not source.exists():
            raise FileNotFoundError(f"Part source not found: {source}")
        archive_path = archive_path or str(source)
        self.add_part(archive_path, source.read_bytes(), content_type="")

    def add_directory(
        self, source_dir: Path, *, prefix: str = "", include_globs: Iterable[str] = ()
    ) -> None:
        """Recursively add every file under ``source_dir`` as a part.

        ``prefix`` is prepended to every archive path — useful for
        the ``Report/CustomVisuals/`` layout. ``include_globs``
        filters files by relative path (e.g. ``["*.json"]``).
        """
        source = Path(source_dir)
        if not source.is_dir():
            raise FileNotFoundError(f"Source directory not found: {source}")
        globs = list(include_globs) if include_globs else None
        for file_path in sorted(source.rglob("*")):
            if not file_path.is_file():
                continue
            rel = file_path.relative_to(source).as_posix()
            if globs and not any(_match_glob(rel, g) for g in globs):
                continue
            archive_path = f"{prefix.rstrip('/')}/{rel}" if prefix else rel
            self.add_file(file_path, archive_path=archive_path)

    # ------------------------------------------------------------------
    # PBIP-folder convenience
    # ------------------------------------------------------------------
    def add_pbip_folder(self, pbip_dir: Path) -> None:
        """Ingest a complete PBIP folder into the template.

        Maps the PBIP components onto the corresponding OPC parts:

        * ``*.SemanticModel/`` → ``DataModelSchema`` (with a stub
          if real Tabular Model JSON is not available — pbi-tools
          is the right tool for compiling TMDL to TMSL).
        * ``*.Report/definition/`` → ``Report/Layout``.
        * ``*.Report/StaticResources/`` → ``Report/StaticResources/...``.
        * ``*.Report/CustomVisuals/`` → ``Report/CustomVisuals/...``.
        """
        pbip_dir = Path(pbip_dir)
        if not pbip_dir.is_dir():
            raise FileNotFoundError(f"PBIP directory not found: {pbip_dir}")

        # Discover the semantic-model and report directories. PBIP
        # conventions use ``<Project>.SemanticModel`` and
        # ``<Project>.Report``.
        semantic_model_dir = _find_component_dir(
            pbip_dir, (".SemanticModel", ".Dataset")
        )
        report_dir = _find_component_dir(pbip_dir, (".Report",))

        # Tabular Model JSON: we don't have one (PBIP carries TMDL
        # text). Emit a stub so Power BI Desktop opens the file as
        # a template and prompts for a data source.
        if semantic_model_dir is not None:
            self.add_data_model_schema()
            self.add_data_model_schema_template()
        else:
            self.add_data_model_schema()

        # DataMashup stub. The real stream requires compiling the
        # TMDL partitions' M expressions; that's pbi-tools' job.
        self.add_data_mashup()

        # Report layout: collapse the PBIR folder structure into
        # the ``Report/Layout`` JSON part Power BI expects.
        if report_dir is not None:
            layout = _build_report_layout_from_pbip(report_dir)
            self.add_report_layout(layout)
            # Carry static resources and custom visuals across.
            static_resources = report_dir / "StaticResources"
            if static_resources.is_dir():
                self.add_directory(static_resources, prefix="Report/StaticResources")
            custom_visuals = report_dir / "CustomVisuals"
            if custom_visuals.is_dir():
                self.add_directory(custom_visuals, prefix="Report/CustomVisuals")
            # Linguistic schema (optional; copy if present).
            linguistic = report_dir / "LinguisticSchema"
            if linguistic.is_file():
                self.add_file(linguistic, archive_path="Report/LinguisticSchema")
        else:
            self.add_report_layout({"pages": [], "settings": {}})

    # ------------------------------------------------------------------
    # Finalisation
    # ------------------------------------------------------------------
    def ensure_manifest_parts(self) -> None:
        """Add the standard manifest parts if the caller didn't."""
        if "Version" not in self._parts:
            self.add_version()
        if "Metadata" not in self._parts:
            self.add_metadata()
        if "Settings" not in self._parts:
            self.add_settings()
        if "SecurityBindings" not in self._parts:
            self.add_security_bindings()
        if "DiagramLayout" not in self._parts:
            self.add_diagram_layout()

    def finalize(self) -> Path:
        """Write the archive to ``output_path`` and close it.

        Returns the absolute path to the written file.
        """
        if self._finalised:
            return self.output_path
        self.ensure_manifest_parts()
        self._write()
        self._finalised = True
        return self.output_path

    def _write(self) -> None:
        """Emit the archive.

        The order of parts in a ZIP file is observable but Power BI
        Desktop doesn't care. We write ``[Content_Types].xml`` LAST
        so a partial archive (if the writer crashes mid-write) is
        easier to recognise as incomplete.
        """
        with zipfile.ZipFile(
            self.output_path, "w", compression=zipfile.ZIP_DEFLATED
        ) as archive:
            # Write all caller-supplied parts first.
            for part_path, body in self._parts.items():
                archive.writestr(part_path, body)
            # Then [Content_Types].xml — Power BI Desktop is strict
            # about this file existing at the archive root.
            archive.writestr("[Content_Types].xml", self._registry.to_xml())
        if self._logger is not None:
            self._logger.info(
                "Wrote OPC archive %s (%d parts)",
                self.output_path,
                len(self._parts) + 1,
            )

    # Inspection helpers used by tests and the CLI exporter.
    @property
    def parts(self) -> Dict[str, bytes]:
        return dict(self._parts)


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------


def _find_component_dir(pbip_dir: Path, suffixes: Iterable[str]) -> Optional[Path]:
    for candidate in pbip_dir.iterdir():
        if candidate.is_dir() and any(
            candidate.name.endswith(suffix) for suffix in suffixes
        ):
            return candidate
    return None


def _build_report_layout_from_pbip(report_dir: Path) -> Dict[str, Any]:
    """Collapse a ``.Report/`` PBIP folder into the ``Report/Layout`` JSON.

    The PBIP folder structure is::

        Report/
            definition.pbir
            definition/
                report.json
                pages/<name>/page.json
                pages/<name>/visuals/visual_*.json

    Power BI's monolithic ``.pbit`` format stores the same data as
    a single ``Report/Layout`` JSON. The mapping is:

    * ``report.json.pages`` → ``Layout.pages[*]``
    * Each ``pages/<name>/page.json`` → embedded into the
      corresponding ``Layout.pages[i]`` entry.
    * Each ``visuals/visual_*.json`` → appended to
      ``Layout.pages[i].visualContainers``.
    """
    definition_dir = report_dir / "definition"
    if not definition_dir.is_dir():
        return {"pages": [], "settings": {}}
    report_json_path = definition_dir / "report.json"
    if not report_json_path.is_file():
        return {"pages": [], "settings": {}}
    report_data = json.loads(report_json_path.read_text(encoding="utf-8"))
    # Ingest each page directory and merge its contents into the
    # corresponding entry of ``report_data.pages``.
    pages_dir = definition_dir / "pages"
    pages = report_data.get("pages") or []
    for page_entry in pages:
        page_name = page_entry.get("name")
        if not page_name:
            continue
        page_dir = pages_dir / page_name
        if not page_dir.is_dir():
            continue
        page_json_path = page_dir / "page.json"
        if page_json_path.is_file():
            page_entry.update(json.loads(page_json_path.read_text(encoding="utf-8")))
        visuals_dir = page_dir / "visuals"
        if visuals_dir.is_dir():
            page_entry["visualContainers"] = [
                json.loads(vis.read_text(encoding="utf-8"))
                for vis in sorted(visuals_dir.glob("visual_*.json"))
            ]
    return report_data


def _match_glob(path: str, glob: str) -> bool:
    """Match a forward-slash ``path`` against a simple ``glob`` pattern.

    Rules:

    * ``*`` matches any characters except ``/``.
    * ``**`` matches any characters including ``/``.
    * ``?`` matches a single character that is not ``/``.

    Implemented as a regex translation rather than :mod:`fnmatch`
    because :mod:`fnmatch` doesn't distinguish ``/``-aware ``*``
    from cross-directory ``**``.
    """
    import re

    # Escape regex metacharacters except the glob ones we want to
    # translate (``*`` and ``?``).
    parts = re.split(r"(\*\*|\*|\?)", glob)
    regex = ""
    for part in parts:
        if part == "*":
            # Single-segment wildcard: any chars except ``/``.
            regex = f"{regex}[^/]*"
        elif part == "**":
            # Cross-segment wildcard: any chars including ``/``.
            regex = f"{regex}.*"
        elif part == "?":
            # Single non-separator character.
            regex = f"{regex}[^/]"
        else:
            regex = f"{regex}{re.escape(part)}"
    return re.fullmatch(regex, path) is not None


def _build_logger() -> Any:
    import logging

    return logging.getLogger(__name__)
